# -*- coding: utf-8 -*-
"""Descripción y claves técnicas en español, escritas de cero.
   Clave = el nombre de Trainerize (así cruza con el volcado).
   'd' = descripción para el cliente · 'c' = claves técnicas (bullets)."""
TEXTOS = {

# ── Movilidad y calentamiento ──────────────────────────────────────────
"90-90 Hip Switch": {"d":"Sentado con las dos rodillas dobladas a 90°, una delante y otra al lado. Deja caer las rodillas al otro lado sin levantar las manos del suelo y vuelve. Es movilidad de cadera, no un estiramiento forzado.","c":["Pecho alto, no te hundas","Lleva las rodillas al suelo, no al aire","Sin rebotes: control"]},
"Bodyweight Alternating Cossack Squat": {"d":"De pie, piernas bien abiertas. Baja hacia un lado doblando esa rodilla mientras la otra pierna queda estirada, y pasa al otro lado sin levantarte del todo.","c":["El talón de la pierna que baja, clavado","La pierna estirada con la punta arriba","Pecho alto todo el recorrido"]},
"Bodyweight Squat To Hinge": {"d":"Baja a sentadilla profunda, y desde ahí estira las rodillas llevando la cadera atrás hasta quedar en bisagra. Vuelve a la sentadilla. Enseña a tu cadera la diferencia entre los dos patrones.","c":["En la bisagra, rodillas casi estiradas","Espalda plana en las dos posiciones","Peso repartido en todo el pie"]},
"Bodyweight Spiderman Lunge To Rotation": {"d":"Desde plancha, lleva un pie junto a la mano del mismo lado. Abre el pecho girando el torso y sube ese brazo al techo. Vuelve y cambia.","c":["La cadera baja, no se queda arriba","Gira desde el pecho, no desde el hombro","La mano de apoyo bien clavada"]},
"Dynamic Hip Opening Flow": {"d":"Encadena zancada, apertura de pecho y perro boca abajo en una secuencia continua. Calienta cadera, tobillo y columna de una vez.","c":["Sin pausas entre posiciones","Respira en cada apertura","Rango cómodo, no máximo"]},
"Mini Band Wall Slides": {"d":"De espaldas a la pared con una banda en las muñecas. Sube los brazos por la pared abriendo contra la banda y baja despacio.","c":["Lumbares pegadas a la pared","Abre contra la banda todo el rato","Sube solo hasta donde no se despegue la espalda"]},
"Mini Band Standing I's": {"d":"De pie, banda en las muñecas. Sube los brazos rectos por delante hasta encima de la cabeza formando una I, abriendo contra la banda.","c":["No arquees la zona lumbar","Pulgares mirando atrás arriba","Baja con la misma lentitud"]},
"Lateral Lunge to T-Rotation": {"d":"Da un paso lateral amplio y siéntate sobre esa pierna. Desde abajo, gira el torso y lleva un brazo al techo. Vuelve y cambia de lado.","c":["La pierna que no trabaja, estirada","Gira cuando ya estés abajo","La vista sigue a la mano"]},
"Glute Side Circle": {"d":"En cuadrupedia, abre una rodilla al lado y dibuja un círculo grande con ella sin mover la cadera. Haz los círculos en los dos sentidos.","c":["El abdomen firme: la cadera no rota","Círculos grandes y lentos","La espalda no se arquea"]},
"Alternating Spiderman lunge to hip lift": {"d":"Desde plancha, pie junto a la mano, y desde ahí sube la cadera estirando la pierna de delante. Vuelve y cambia.","c":["En la subida, pierna casi recta","Empuja el suelo con las manos","Alterna sin descansar en medio"]},
"Downward Dog to Scorpion": {"d":"Desde perro boca abajo, sube una pierna, dobla la rodilla y cruza el pie hacia el lado contrario abriendo la cadera. Vuelve y cambia.","c":["Manos firmes, brazos estirados","Abre desde la cadera, no desde la lumbar","Sin forzar: hasta donde llegues"]},
"Cossack Squat to T-Spine Reach": {"d":"Sentadilla cosaco a un lado y, desde abajo, sube el brazo del mismo lado al techo abriendo el pecho. Vuelve arriba y repite al otro.","c":["Talón clavado al bajar","El alcance sale del pecho","La otra mano hacia la punta del pie"]},
"Cat to Cow": {"d":"En cuadrupedia, alterna redondear la espalda hacia arriba y hundirla abriendo el pecho, al ritmo de la respiración.","c":["Mueve vértebra a vértebra","Suelta el aire al redondear","Las manos bajo los hombros"]},
"Cobra": {"d":"Boca abajo, manos junto a las costillas. Despega el pecho del suelo estirando los brazos sin despegar la cadera.","c":["La cadera pegada al suelo","Hombros lejos de las orejas","Sube solo hasta donde no moleste"]},
"Table Top Half Arm Thoracic Rotation": {"d":"En cuadrupedia, baja a los antebrazos. Una mano detrás de la cabeza y gira el codo hacia el techo, luego hacia el suelo.","c":["La cadera quieta sobre las rodillas","El giro viene del pecho","Sigue el codo con la mirada"]},
"SuperBand Dislocates": {"d":"Agarra una banda con las manos muy separadas y pásala de delante a atrás por encima de la cabeza, con los brazos estirados.","c":["Brazos rectos todo el recorrido","Cuanto más juntas las manos, más difícil","Sin encoger los hombros"]},
"Dumbbell Standing Shoulder External Rotations": {"d":"De pie, codos pegados al cuerpo a 90°. Abre los antebrazos hacia fuera y vuelve despacio. Mancuerna ligera: esto es salud de hombro.","c":["Los codos no se separan del costado","Peso ligero, control alto","Vuelve frenando, no soltando"]},
"Dumbbell External Rotation on Side": {"d":"Tumbado de lado, codo del brazo de arriba pegado a la cintura. Gira el antebrazo hacia el techo y baja con control.","c":["El codo clavado en la cintura","Solo gira el antebrazo","Sin ayudarte con el cuerpo"]},

# ── Agilidad, pliometría y cardio ──────────────────────────────────────
"Lateral Shuttle Run": {"d":"Desplázate lateralmente entre dos puntos, cadera baja y pasos rápidos, sin cruzar los pies.","c":["Cadera baja todo el rato","Los pies no se cruzan","Frena y sal: ahí está el trabajo"]},
"Shuttle Run": {"d":"Ida y vuelta corta a máxima velocidad, tocando el suelo en cada cambio de sentido.","c":["Baja a tocar, no te dobles solo","Sal fuerte en cada giro","Pasos cortos al frenar"]},
"Jump Squat to Reverse Lunge": {"d":"Sentadilla con salto y, al caer, un paso atrás a zancada. Vuelve y repite alternando la pierna.","c":["Cae blando, rodilla alineada","La zancada llega, no se desploma","Encadena sin pausa"]},
"1/2 Kneel to Lateral Bound": {"d":"Desde media rodilla, impúlsate lateralmente y cae sobre una pierna, aguantando el aterrizaje.","c":["Aguanta el aterrizaje 1 segundo","Rodilla nunca hacia dentro","Salta lejos, no alto"]},
"Bosu Lateral Bounce to Squat Jump": {"d":"Rebota lateralmente apoyando un pie en el BOSU, sal hacia el suelo y encadena un salto en sentadilla.","c":["El pie del BOSU, centrado","No pares entre rebote y salto","Cae con las rodillas blandas"]},
"Broad Jump": {"d":"Salto horizontal con los dos pies: brazos atrás, cadera atrás y salta lo más lejos que puedas. Aguanta la caída.","c":["Los brazos acompañan el salto","Cae con cadera atrás y rodillas blandas","Calidad antes que distancia"]},
"Squat Jump": {"d":"Baja a media sentadilla y salta vertical. Amortigua la caída volviendo a la posición de salida.","c":["Empuja todo el pie contra el suelo","Cae en silencio","Rodillas en línea con los pies"]},
"BOSU Alternating Lateral Squat Shuffle": {"d":"Desplázate de lado a lado pasando por encima del BOSU, en posición de media sentadilla.","c":["Cadera baja siempre","Pisa el centro del BOSU","Mira al frente, no a los pies"]},
"Running": {"d":"Carrera continua a intensidad moderada: deberías poder hablar, pero con esfuerzo.","c":["Zancada cómoda, no larga","Hombros sueltos","Respiración por la nariz si puedes"]},
"Half Burpee with Dumbbell": {"d":"Con las mancuernas en el suelo, salta atrás a plancha, vuelve y ponte de pie. Sin flexión.","c":["La cadera no se hunde en plancha","Salta los pies juntos","Ritmo constante"]},
"Dumbbell Burpee Clean to Press": {"d":"Burpee con mancuernas y, al levantarte, cargas el peso a los hombros y lo empujas sobre la cabeza.","c":["La cargada sale de la cadera","Abdomen firme en el empuje","Deja el peso controlado, no lo tires"]},

# ── Tren inferior ──────────────────────────────────────────────────────
"Dumbbell Front Squat": {"d":"Mancuernas a la altura de los hombros. Baja en sentadilla manteniendo el torso vertical y sube empujando el suelo.","c":["Codos altos: si caen, el pecho cae","Rodillas en línea con los pies","Baja hasta donde la espalda aguante plana"]},
"Dumbbell Straight Leg Deadlift": {"d":"De pie con las mancuernas delante. Lleva la cadera atrás bajando el peso pegado a las piernas, con las rodillas casi rectas. Sube apretando glúteos.","c":["Las mancuernas rozan la pierna","Espalda plana, pecho arriba","Notas el estiramiento detrás del muslo"]},
"Plate Hip Thrust": {"d":"Espalda apoyada en un banco, disco sobre la cadera. Sube la cadera hasta alinear tronco y muslos y baja con control.","c":["Apoya el peso en los talones","Barbilla al pecho, mirada al frente","Aprieta arriba 1 segundo"]},
"Mini Band Wall Sit with Abductions": {"d":"Sentadilla isométrica contra la pared con una banda por encima de las rodillas. Sin moverte, abre y cierra las rodillas contra la banda.","c":["Muslos paralelos al suelo","La espalda no se despega","Abre con control, no a tirones"]},
"Mini Band Side Lying Hip Abduction": {"d":"Tumbado de lado con la banda en los tobillos, sube la pierna de arriba sin girar la cadera y baja despacio.","c":["El cuerpo no se va hacia atrás","Sube hasta donde la cadera no rote","La bajada, igual de lenta"]},
"Dumbbell Single Leg Calf Raise": {"d":"De pie sobre un escalón con una mancuerna en la mano, sube el talón lo máximo posible y baja hasta estirar el gemelo.","c":["Rango completo: arriba y abajo","Apóyate para no balancearte","Pausa arriba, pausa abajo"]},
"Angled Machine Leg Press": {"d":"En la prensa, baja el peso hacia el pecho doblando las rodillas y empuja sin llegar a bloquearlas.","c":["La lumbar pegada al respaldo","No bloquees las rodillas arriba","Baja hasta donde la cadera no se levante"]},
"Machine Seated Leg Extension": {"d":"Sentado, con la almohadilla justo encima del tobillo, estira las rodillas del todo y baja con control.","c":["Estira completo arriba","No dejes caer el peso","Espalda apoyada en el respaldo"]},
"Machine Seated Leg Curl": {"d":"Sentado con las piernas estiradas sobre la almohadilla, flexiona las rodillas llevándolas abajo y vuelve despacio.","c":["Punta del pie hacia ti","La cadera no se despega","La vuelta, frenada"]},
"Machine Seated Hip Adduction": {"d":"Sentado con las rodillas abiertas contra las almohadillas, júntalas apretando y vuelve con control.","c":["Aprieta al juntar","Abre hasta notar el estiramiento","Espalda apoyada"]},
"Machine Seated Calf Raise": {"d":"Sentado con la almohadilla sobre los muslos y la punta del pie en el escalón, sube los talones al máximo y baja hasta estirar.","c":["Rango completo, no medio","Pausa arriba","Sin rebotar abajo"]},
"Hip Thrust Machine": {"d":"Sentado en la máquina con el apoyo sobre la cadera, empuja hasta alinear tronco y muslos apretando glúteos.","c":["Empuja con los talones","Aprieta arriba antes de bajar","Sin arquear la lumbar"]},
"Smith Machine Deadlift": {"d":"Barra a la altura de la cadera en el multipower. Baja llevando la cadera atrás con la espalda plana y sube empujando el suelo.","c":["La barra roza la pierna","Pecho arriba en todo el recorrido","Sube cadera y pecho a la vez"]},
"Smith Machine Sumo Deadlift": {"d":"Igual que el peso muerto pero con los pies bien abiertos y las puntas hacia fuera. Trabaja más glúteo y aductor.","c":["Rodillas hacia fuera, siguiendo el pie","Espalda plana desde el inicio","Termina apretando glúteos"]},
"Smith Machine Back Squat": {"d":"Barra sobre la espalda alta en el multipower. Baja controlando hasta romper el paralelo y sube empujando el suelo.","c":["Pies algo adelantados en el multipower","Rodillas siguen la punta del pie","No rebotes abajo"]},
"Landmine RDL": {"d":"Peso muerto rumano con la barra anclada. Lleva la cadera atrás bajando la barra con las rodillas casi rectas.","c":["El recorrido lo marca la barra","Espalda plana siempre","Sube con glúteo, no con lumbar"]},
"Dumbbell Bulgarian Split Squat": {"d":"Pie de atrás sobre un banco, mancuernas a los lados. Baja la rodilla de atrás hacia el suelo y sube empujando con la pierna de delante.","c":["El pie de delante, bastante adelantado","Torso ligeramente inclinado","Empuja con el talón de delante"]},
"Cable Glute Crossover Kickback": {"d":"De pie en la polea baja, lleva la pierna atrás y en diagonal cruzando la línea media. Aprieta arriba y vuelve despacio.","c":["La pierna sale recta y en diagonal","No arquees la lumbar","Aprieta el glúteo arriba"]},
"Dumbbell Hip Thrust": {"d":"Espalda en el banco y mancuerna sobre la cadera. Sube hasta alinear tronco y muslos y baja con control.","c":["Sujeta la mancuerna con las dos manos","Empuja con los talones","Barbilla al pecho"]},
"Dumbbell Reverse Lunge": {"d":"Da un paso atrás y baja la rodilla hacia el suelo. Vuelve empujando con la pierna de delante.","c":["El paso atrás, largo","La rodilla de atrás casi toca","Torso vertical"]},
"Dumbbell Sumo Deadlift": {"d":"Una mancuerna entre los pies, piernas abiertas y puntas hacia fuera. Baja con la espalda plana y sube apretando glúteos.","c":["Rodillas hacia fuera","La mancuerna, entre los pies","Espalda plana, pecho arriba"]},
"Dumbbell Glute Bridge": {"d":"Tumbado boca arriba con la mancuerna sobre la cadera, sube hasta alinear tronco y muslos y baja sin apoyar del todo.","c":["Talones cerca del glúteo","Aprieta arriba","No arquees la lumbar"]},
}

TEXTOS.update({
# ── Empuje: pecho y hombro ─────────────────────────────────────────────
"Dumbbell Bench Press": {"d":"Tumbado en banco plano con una mancuerna en cada mano. Baja hasta que los codos queden a la altura del pecho y empuja hasta juntarlas arriba.","c":["Codos a unos 45°, no abiertos del todo","Escápulas apretadas contra el banco","Baja controlando, sube con intención"]},
"Dumbbell Incline Bench Press": {"d":"Banco a 45°. Empuja las mancuernas desde la altura del pecho hasta arriba. Carga más la parte alta del pectoral.","c":["El banco a 45°, no más","No dejes caer las mancuernas abajo","Muñecas firmes sobre el codo"]},
"Dumbbell Floor Press": {"d":"Tumbado en el suelo con las mancuernas a la altura del pecho. Empuja arriba y baja hasta que el codo toque el suelo.","c":["El codo toca y sales, sin rebotar","Recorrido más corto: puedes más peso","Lumbar pegada al suelo"]},
"Dumbbell Glute Bridge Chest Press": {"d":"Boca arriba con la cadera en alto, aguantando el puente mientras empujas las mancuernas sobre el pecho.","c":["La cadera no baja en ninguna repetición","Aprieta glúteos todo el rato","Empuja recto, no hacia la cara"]},
"Machine Seated Chest Press": {"d":"Sentado con la espalda apoyada, empuja las agarraderas hasta estirar los brazos y vuelve controlando.","c":["Agarraderas a la altura del pecho","No bloquees los codos del todo","La espalda no se despega"]},
"Machine Seated Chest Fly": {"d":"Sentado, con los codos ligeramente doblados, junta las agarraderas delante del pecho y abre despacio.","c":["El ángulo del codo no cambia","Aprieta al juntar","Abre hasta notar estiramiento, sin pasarte"]},
"Cable Standing Crossover Chest Fly": {"d":"De pie entre dos poleas altas, junta las manos delante del pecho cruzándolas ligeramente y vuelve con control.","c":["Un pie adelantado para estabilizar","Codos algo doblados y fijos","El pecho hace el trabajo, no el hombro"]},
"Smith Machine Bench Press": {"d":"Press de banca con la barra guiada del multipower. Baja hasta rozar el pecho y empuja.","c":["Coloca el banco para que la barra caiga al pecho","Escápulas apretadas","No rebotes en el pecho"]},
"Smith Machine Incline Bench Press": {"d":"Igual pero con el banco a 45°. La barra guiada te deja centrarte en empujar.","c":["La barra baja a la clavícula, no al cuello","Pies firmes en el suelo","Sube sin bloquear del todo"]},
"Push Up": {"d":"Manos algo más anchas que los hombros. Baja el pecho al suelo manteniendo el cuerpo en línea y empuja.","c":["El cuerpo es una tabla: no hundas la cadera","Codos a 45°, no en cruz","Baja hasta el pecho, no medio camino"]},
"Clapping Push Up": {"d":"Flexión explosiva: empuja tan fuerte que las manos despeguen y da una palmada antes de caer.","c":["Cae con los codos blandos","Abdomen firme: la cadera no se hunde","Pocas repeticiones, todas explosivas"]},
"Bench Plyo Push Ups": {"d":"Flexión con las manos en un banco, empujando fuerte para que despeguen del apoyo.","c":["El banco hace el ejercicio más accesible","Cuerpo en línea","Amortigua al caer"]},
"Dip": {"d":"En paralelas, baja el cuerpo hasta que el brazo pase la paralela y empuja hasta estirar.","c":["Ligera inclinación adelante para el pecho","Hombros lejos de las orejas","Baja hasta donde no moleste el hombro"]},
"Plate Weighted Dip": {"d":"Fondos con un cinturón lastrado. Mismo movimiento, más carga.","c":["Añade peso solo si dominas el fondo limpio","Controla la bajada","No rebotes abajo"]},
"Machine Seated Shoulder Press": {"d":"Sentado, agarraderas a la altura de los hombros. Empuja sobre la cabeza y baja controlando.","c":["Espalda apoyada, sin arquear","Baja hasta que el codo quede a 90°","No bloquees arriba"]},
"Machine Seated Parallel Grip Shoulder Press": {"d":"Press de hombro con las palmas mirándose. Suele ser más amable con el hombro.","c":["Codos por delante del cuerpo","Abdomen firme","Sin arquear la lumbar"]},
"Smith Machine Seated Shoulder Press": {"d":"Sentado bajo la barra guiada, empuja desde los hombros hasta arriba.","c":["La barra baja por delante de la cara","Espalda apoyada","Empuje simétrico"]},
"Dumbbell Seated Shoulder Press": {"d":"Sentado con respaldo, mancuernas a la altura de los hombros. Empuja arriba sin chocarlas y baja con control.","c":["Muñeca sobre el codo","Sin arquear la lumbar","Baja hasta la altura de la oreja"]},
"Dumbbell Seated Arnold Press": {"d":"Empiezas con las palmas hacia ti y giras las muñecas mientras empujas, acabando con las palmas al frente.","c":["El giro acompaña la subida","Peso menor que en un press normal","Control en la vuelta"]},
"Cable Lateral Raise": {"d":"De pie junto a la polea baja, sube el brazo lateralmente hasta la altura del hombro y baja despacio.","c":["Codo ligeramente doblado y fijo","Sube hasta el hombro, no más","No te balancees para subir"]},
"Machine Lateral Raise": {"d":"Sentado en la máquina, con los codos en las almohadillas, sube hasta que el brazo quede paralelo al suelo.","c":["Empuja con el codo, no con la mano","Hombros abajo","Baja frenando"]},
"Dumbbell Alternating Lateral Raise to Front Raise": {"d":"Sube las mancuernas a los lados hasta el hombro, baja, y súbelas por delante. Alterna las dos direcciones.","c":["Peso ligero: son hombros","Sin impulso de cadera","Baja siempre con control"]},
"Seated Dumbbell Front Raise to Lateral Raise": {"d":"Sentado, sube las mancuernas por delante hasta el hombro, baja, y repite hacia los lados.","c":["Sentado no puedes hacer trampa con la cadera","Sube solo hasta el hombro","Muñecas neutras"]},
"Dumbbell Seated Front Raise": {"d":"Sentado, sube las mancuernas rectas por delante hasta la altura del hombro y baja despacio.","c":["Brazos casi rectos","Sin arquear la espalda","Para en el hombro"]},
"Kettlebell Single Arm Clean and Press": {"d":"Cargas la kettlebell al hombro desde el suelo y, desde ahí, la empujas sobre la cabeza. Todo a una mano.","c":["La cargada sale de la cadera","La kettlebell descansa en el antebrazo","Abdomen firme en el empuje"]},
"Kettlebell Alternating Press": {"d":"Con una kettlebell en cada hombro, empuja una y otra alternando, sin perder la postura.","c":["El que no empuja aguanta firme","Sin inclinarte al lado","Abdomen apretado"]},
"Kettlebell Alternating Halo": {"d":"Rodea la cabeza con la kettlebell describiendo un círculo pegado, alternando el sentido.","c":["El círculo pegado a la cabeza","Solo se mueven los brazos","Abdomen firme"]},

# ── Tracción: espalda y bíceps ─────────────────────────────────────────
"Bench Plank Single Arm Row": {"d":"En plancha con las manos en un banco, rema una mancuerna hacia la cadera manteniendo la cadera quieta.","c":["La cadera no rota al remar","Codo pegado al cuerpo","Baja con control"]},
"Dumbbell Single Arm Row": {"d":"Una rodilla y una mano en el banco, espalda plana. Rema la mancuerna hacia la cadera y baja estirando.","c":["Tira con el codo, no con la mano","La espalda se queda plana","Aprieta la escápula arriba"]},
"SuperBand Single Arm Row": {"d":"Con la banda anclada al frente, tira hacia el costado llevando el codo atrás y vuelve con control.","c":["El pecho se abre al tirar","Sin girar el torso","La banda tensa desde el inicio"]},
"Kettlebell Alternating Bent Over Row": {"d":"Inclinado con la espalda plana, rema una kettlebell y luego la otra, sin levantar el torso.","c":["El torso no sube entre repeticiones","Codo pegado al cuerpo","Aprieta arriba"]},
"Dumbbell Incline Bench High Row": {"d":"Pecho apoyado en el banco inclinado, rema las mancuernas abriendo los codos a la altura del hombro.","c":["Codos altos: es remo alto","El pecho no se despega","Aprieta las escápulas"]},
"Machine Seated Single Arm Neutral Grip Row": {"d":"Sentado con el pecho apoyado, rema con una mano hacia el costado con la palma mirando dentro.","c":["El pecho no se despega del apoyo","Estira del todo al volver","Sin girar el torso"]},
"Cable Seated Wide Grip Row": {"d":"Sentado, agarre ancho, tira hacia el abdomen juntando las escápulas y vuelve estirando.","c":["Pecho arriba, no te encorves","Tira con la espalda, no con los brazos","No te balancees"]},
"Cable Seated Close Row": {"d":"Sentado con agarre estrecho, tira hacia el abdomen manteniendo el torso vertical.","c":["Codos pegados al cuerpo","Aprieta las escápulas al final","Vuelve estirando del todo"]},
"Cable Seated Close Grip Row": {"d":"Remo sentado en polea con agarre cerrado, llevando las manos al abdomen.","c":["Torso vertical, sin mecerse","Tira desde el codo","Estira completo al volver"]},
"Wide Grip Lat Pulldown": {"d":"Agarre ancho, tira la barra al pecho abriendo el codo hacia abajo y vuelve estirando los brazos.","c":["Lleva la barra al pecho, no a la nuca","Pecho arriba, ligera inclinación atrás","Sin tirones"]},
"Wide Grip Pull Up": {"d":"Colgado con agarre ancho, sube hasta pasar la barbilla de la barra y baja estirando del todo.","c":["Empieza colgando, brazos estirados","Sube con el pecho, no con la barbilla","Sin balancearte"]},
"Pull Up": {"d":"Colgado con las palmas al frente, sube hasta pasar la barbilla y baja controlando.","c":["Escápulas abajo antes de tirar","Sube el pecho hacia la barra","Baja frenando"]},
"Plate Weighted Wide Grip Pull Up": {"d":"Dominada con cinturón lastrado. Mismo movimiento, más carga.","c":["Añade peso solo si haces dominadas limpias","Rango completo, siempre","Sin impulso de piernas"]},
"Machine Assisted Wide Grip Pull Up": {"d":"Dominada en máquina asistida: cuanto más peso pones, más ayuda recibes.","c":["Más peso = más fácil","Rango completo: estira abajo","Sube con la espalda"]},
"Machine Assisted Parallel Grip Pull Up": {"d":"Dominada asistida con las palmas mirándose. Suele resultar más cómoda de hombro.","c":["Agarre neutro, codos cerca","Estira del todo abajo","Sube hasta pasar la barbilla"]},
"Bar Hang": {"d":"Colgado de la barra con los brazos y las piernas estiradas. Aguanta el tiempo marcado.","c":["Hombros activos, no colgando muertos","Respira","Si te quema el agarre, es normal"]},
"Machine Seated Reverse Fly": {"d":"Sentado con el pecho apoyado, abre los brazos hacia atrás hasta la altura del hombro y vuelve.","c":["Codos ligeramente doblados","Aprieta las escápulas","Sin encoger el cuello"]},
"Cable Rope Face Pull": {"d":"Desde la polea alta, tira de la cuerda hacia la cara separando las manos y abriendo los codos.","c":["Los codos acaban altos","Separa las manos al final","Sin arquear la espalda"]},
"Cable Shrug": {"d":"De pie en la polea baja, sube los hombros hacia las orejas sin doblar los codos y baja despacio.","c":["Brazos estirados todo el rato","Sube y aguanta un instante","No gires los hombros"]},
"Smith Machine Shrug": {"d":"Con la barra guiada delante de los muslos, sube los hombros lo máximo y baja con control.","c":["Brazos rectos","Aguanta arriba","Sin impulso de piernas"]},
"Dumbbell Shrug": {"d":"Mancuernas a los lados, sube los hombros hacia las orejas y baja estirando.","c":["Brazos estirados","Pausa arriba","Baja del todo"]},
"Cable Bicep Curl": {"d":"De pie frente a la polea baja, flexiona los codos llevando la barra a los hombros y baja despacio.","c":["Codos pegados al costado","Sin mecer el cuerpo","Baja frenando"]},
"Dumbbell Hammer Curl": {"d":"Mancuernas con las palmas mirándose. Sube hacia el hombro sin girar la muñeca.","c":["Palma neutra todo el recorrido","Codos quietos","Baja controlando"]},
"Dumbbell Alternating Hammer Curl": {"d":"Curl martillo alternando brazos, con la palma mirando dentro en todo el recorrido.","c":["El brazo que espera, quieto","Sin balanceo","Baja despacio"]},
"Dumbbell Alternating Bicep Curl": {"d":"Curl alternando brazos, girando la muñeca hacia arriba al subir.","c":["Codos pegados al cuerpo","El giro acompaña la subida","Baja del todo"]},
"Dumbbell Incline Alternating Curl": {"d":"Tumbado en banco inclinado, con los brazos colgando, sube una mancuerna y luego la otra.","c":["El brazo cuelga del todo abajo","Los codos no se van adelante","Estiramiento máximo abajo"]},
"Barbell Preacher Curl": {"d":"Brazos apoyados en el banco predicador. Sube la barra hacia los hombros y baja hasta casi estirar.","c":["Los codos no se despegan del banco","No estires del todo abajo","Baja lento"]},
"EZ Bar Preacher Curl": {"d":"Igual pero con barra Z: el agarre en ángulo es más cómodo para la muñeca.","c":["Axilas pegadas al apoyo","Baja controlando","Rango completo"]},
"Machine Preacher Curl": {"d":"Sentado con los brazos en la almohadilla, flexiona hacia los hombros y baja despacio.","c":["Brazos bien apoyados","Sin despegar los codos","La bajada, frenada"]},
"Cable V Bar Tricep Pushdown": {"d":"De pie frente a la polea alta, empuja la barra hacia abajo estirando los codos y vuelve.","c":["Codos pegados al costado","Solo se mueve el antebrazo","Estira del todo abajo"]},
"Cable Straight Bar Tricep Pushdown": {"d":"Igual con barra recta: empuja hasta estirar los brazos junto a los muslos.","c":["Codos fijos","Sin inclinarte para empujar","Vuelve con control"]},
"Cable V-Bar Overhead Tricep Extension": {"d":"De espaldas a la polea, con la barra detrás de la cabeza, estira los brazos hacia delante.","c":["Codos apuntando al frente","Abdomen firme, sin arquear","Estira completo"]},
"Cable Single Arm Standing Overhead Tricep Extension": {"d":"Lo mismo con una sola mano, llevando el codo detrás de la cabeza.","c":["El codo apunta al frente","El hombro no se mueve","Cambia de mano al terminar"]},
"Dumbbell Seated Overhead Tricep Extension": {"d":"Sentado, con la mancuerna sobre la cabeza, baja detrás de la nuca doblando los codos y estira.","c":["Codos hacia el techo y cerca","Sin arquear la lumbar","Baja hasta notar el tríceps"]},
"Band Anchored Single Arm Tricep Kickback": {"d":"Con la banda anclada delante, inclínate y lleva la mano atrás hasta estirar el brazo.","c":["El codo queda alto y fijo","Solo se mueve el antebrazo","Aprieta al estirar"]},
"SuperBand Anchored Tricep Pushdown": {"d":"Banda anclada arriba: empuja hacia abajo hasta estirar los codos junto a los muslos.","c":["Codos al costado","Estira del todo","Vuelve frenando"]},
"Band Internal Shoulder Rotation (90 degrees)": {"d":"Codo a 90° pegado al costado, con la banda al lado. Gira el antebrazo hacia el ombligo y vuelve.","c":["El codo no se separa","Movimiento corto y controlado","Banda ligera"]},
"Cable External Rotation": {"d":"Codo a 90° pegado al costado, gira el antebrazo hacia fuera contra la polea y vuelve.","c":["Codo clavado en la cintura","Carga ligera","Solo gira el antebrazo"]},
})

TEXTOS.update({
# ── Core ───────────────────────────────────────────────────────────────
"Bench Knee Tuck to V Up": {"d":"Sentado en el borde del banco, manos atrás. Lleva las rodillas al pecho y luego estira las piernas subiendo el torso en V.","c":["El abdomen manda, no los brazos","No dejes caer los pies al suelo","Espalda sin redondear del todo"]},
"Bicycle Crunch": {"d":"Boca arriba, lleva el codo hacia la rodilla contraria alternando, con las piernas pedaleando en el aire.","c":["Gira desde las costillas, no del cuello","La pierna que se estira, baja","Lento: no es velocidad"]},
"High Plank Jacks": {"d":"En plancha alta, abre y cierra los pies saltando, sin que la cadera se mueva.","c":["La cadera no sube ni baja","Manos bajo los hombros","Abdomen apretado todo el rato"]},
"Pallof Press": {"d":"De lado a la polea, con las manos en el pecho. Empuja al frente resistiendo el giro y vuelve.","c":["No dejes que el torso gire: ese es el ejercicio","Cadera y hombros al frente","Respira en el empuje"]},
"Dip Machine Bent Leg Raise": {"d":"Apoyado en las paralelas, sube las rodillas hacia el pecho y baja con control.","c":["Sin balancearte","Sube desde el abdomen, no desde la cadera","Baja frenando"]},
"Dip Machine Straight Leg Raise": {"d":"Igual pero con las piernas estiradas: más palanca, más difícil.","c":["Piernas rectas todo el recorrido","Sin impulso","Baja despacio"]},
"Ab Roller Wheel Abdominal Roll Out": {"d":"De rodillas con la rueda en las manos, rueda hacia delante todo lo que puedas sin que la cadera se hunda, y vuelve.","c":["La lumbar no se arquea: si se arquea, has ido lejos","Llega hasta donde controles","Vuelve tirando del abdomen"]},
"Seated Machine Ab Crunch": {"d":"Sentado en la máquina, flexiona el tronco llevando las costillas hacia la cadera y vuelve con control.","c":["Acorta la distancia costillas-cadera","Sin tirar del cuello","Vuelve frenando"]},
"Cross Body Mountain Climber": {"d":"En plancha alta, lleva la rodilla hacia el codo contrario alternando rápido.","c":["La cadera no sube","Manos firmes bajo los hombros","Ritmo vivo pero limpio"]},
"Mountain Climber": {"d":"En plancha alta, lleva las rodillas al pecho alternando, como si corrieras en el sitio.","c":["Cuerpo en línea","Sin rebotar la cadera","Respira constante"]},
"Knee to Elbow Crunch": {"d":"Boca arriba con las manos en la cabeza, acerca las rodillas y los codos a la vez.","c":["No tires del cuello","Acorta la distancia, no subas por subir","Baja sin apoyar del todo"]},
"Bench V Sit Leg Raise": {"d":"Sentado en el borde del banco, sujeto con las manos, sube y baja las piernas manteniendo el torso inclinado atrás.","c":["Espalda recta, no redondeada","Las piernas no tocan el suelo","Control en la bajada"]},
"Plank To Push Up": {"d":"Desde plancha de antebrazos, sube a plancha alta apoyando mano a mano, y vuelve a bajar. Alterna el brazo que inicia.","c":["La cadera no se balancea","Alterna el brazo que sube","Pies algo separados ayuda"]},
"Bodyweight Deadbug": {"d":"Boca arriba con brazos y piernas arriba. Baja el brazo y la pierna contrarios sin que la lumbar se despegue, y vuelve.","c":["La lumbar pegada al suelo: es la clave","Baja solo hasta donde aguante","Respira, no contengas"]},
"Seated Hip Twist": {"d":"Sentado con el torso inclinado atrás y los pies elevados, gira el tronco de lado a lado.","c":["El giro sale de las costillas","Pecho arriba, sin encorvarte","Controla, no lances"]},
"Plate Russian Twist": {"d":"Sentado con el torso atrás y un disco en las manos, gira de lado a lado llevando el disco junto a la cadera.","c":["Gira el torso, no solo los brazos","Espalda recta","Pies arriba si quieres más"]},

# ── Tren inferior restante ─────────────────────────────────────────────
"Dumbbell Stationary Lunge": {"d":"En posición de zancada fija, baja la rodilla de atrás hacia el suelo y sube, sin mover los pies entre repeticiones.","c":["Torso vertical","La rodilla de atrás casi toca","Empuja con el talón de delante"]},
"Bench Hip Thrust": {"d":"Espalda apoyada en el banco, sube la cadera hasta alinear tronco y muslos apretando glúteos.","c":["El banco a la altura de las escápulas","Barbilla al pecho","Aprieta arriba"]},
"Bodyweight Deadlift": {"d":"Patrón de bisagra sin carga: cadera atrás, espalda plana, baja el torso y vuelve apretando glúteos.","c":["La cadera va atrás, no abajo","Espalda plana siempre","Rodillas apenas dobladas"]},
"Body Weight Calf Raise": {"d":"De pie, sube los talones todo lo que puedas y baja hasta estirar el gemelo.","c":["Rango completo","Pausa arriba","Apóyate si pierdes el equilibrio"]},
"Dumbbell Deadlift": {"d":"Mancuernas delante de las piernas. Baja llevando la cadera atrás con la espalda plana y sube empujando el suelo.","c":["Las mancuernas rozan la pierna","Pecho arriba","Termina apretando glúteos"]},
"Seated Leg Press": {"d":"Sentado en la prensa, empuja la plataforma estirando las piernas sin bloquear y vuelve controlando.","c":["Lumbar pegada al respaldo","No bloquees las rodillas","Baja hasta donde la cadera no se levante"]},
"Machine Lying Leg Curl": {"d":"Tumbado boca abajo con la almohadilla sobre los tobillos, flexiona las rodillas y baja despacio.","c":["La cadera pegada al banco","Punta del pie hacia ti","Baja frenando"]},
"Leg Press Machine Calf Raise": {"d":"En la prensa, con la punta del pie en el borde de la plataforma, empuja con los gemelos y baja estirando.","c":["Rodillas casi rectas, no las dobles","Rango completo","Sin rebotar"]},
"Machine Standing Calf Raise": {"d":"De pie en la máquina, sube los talones al máximo y baja hasta notar el estiramiento.","c":["Rodillas rectas","Pausa arriba","Baja del todo"]},
"Barbell Romanian Deadlift": {"d":"Barra delante de los muslos. Lleva la cadera atrás bajando la barra pegada a la pierna, con las rodillas casi rectas.","c":["La barra roza la pierna","Espalda plana, pecho arriba","Para cuando la espalda quiera redondearse"]},
"90-90 to Hip Raise": {"d":"Desde la posición 90-90 sentado, empuja con la pierna de atrás para despegar la cadera del suelo.","c":["Aprieta el glúteo arriba","Sin arquear la lumbar","Control en la bajada"]},
"Alternating Lunge Hops": {"d":"En zancada, salta y cambia de pierna en el aire, cayendo en zancada con la otra delante.","c":["Cae blando, rodilla alineada","Torso vertical","Encadena sin pararte"]},
"Quadruped Hip Circles": {"d":"En cuadrupedia, levanta una rodilla al lado y dibuja círculos grandes con la cadera.","c":["El torso no se mueve","Círculos amplios","Los dos sentidos"]},
"Bodyweight Cossack Squat": {"d":"Piernas bien abiertas, baja hacia un lado doblando esa rodilla con la otra pierna estirada.","c":["Talón clavado","La pierna estirada con la punta arriba","Pecho alto"]},
"Squat to Hinge": {"d":"Alterna sentadilla profunda y bisagra de cadera, para sentir la diferencia entre los dos patrones.","c":["En la bisagra, rodillas casi rectas","Espalda plana siempre","Sin prisa"]},
"1/2 Kneel to High Knee Hop": {"d":"Desde media rodilla, impúlsate a ponerte de pie y encadena un salto subiendo la rodilla contraria.","c":["Sube de un impulso, sin apoyar las manos","Cae blando","Alterna el lado"]},
"Bear Squat to Spinal Wave": {"d":"En posición de oso (rodillas a un palmo del suelo), lleva la cadera a los talones y vuelve ondulando la columna.","c":["Las rodillas no tocan el suelo","La onda pasa por toda la espalda","Lento"]},
"Bear to Step Through": {"d":"Desde posición de oso, pasa una pierna por debajo del cuerpo hasta sentarte de lado, y vuelve.","c":["Movimiento fluido, sin pausas","Las manos firmes","Alterna los lados"]},
"Dumbbell Clean to Press": {"d":"Desde las mancuernas a la altura de las rodillas, cárgalas a los hombros con un golpe de cadera y empújalas arriba.","c":["La cadera da el impulso","Recibe con las rodillas blandas","El empuje, sin arquear"]},
"Dumbbell Burpee with Curl to Press": {"d":"Burpee con mancuernas y, al levantarte, un curl seguido de un press sobre la cabeza.","c":["Encadena sin pausas","Abdomen firme en el press","Peso que te deje hacerlo limpio"]},

# ── Movilidad y estiramientos restantes ────────────────────────────────
"Hinge to T-Rotation": {"d":"Bisagra de cadera y, desde abajo, gira el torso subiendo un brazo al techo. Vuelve y alterna.","c":["Espalda plana en la bisagra","El giro sale del pecho","La vista sigue a la mano"]},
"Quadruped Scapular Push Up": {"d":"En cuadrupedia con los brazos rectos, hunde y saca el pecho moviendo solo las escápulas.","c":["Los codos NO se doblan","El movimiento es pequeño","Notas el trabajo entre los omóplatos"]},
"Trunk Rotation": {"d":"De pie, gira el torso de lado a lado dejando que los brazos acompañen, sin mover la cadera.","c":["La cadera mira al frente","Gira desde la columna","Sin lanzar los brazos"]},
"Static Pigeon Stretch": {"d":"Una pierna doblada delante y la otra estirada atrás. Baja el peso sobre la cadera de delante y aguanta.","c":["No fuerces: busca tensión, no dolor","Apóyate en los antebrazos si llegas","Respira y suelta"]},
"Child's Pose": {"d":"De rodillas, siéntate sobre los talones y estira los brazos al frente apoyando la frente.","c":["Relaja hombros y cuello","Respira hondo","Aguanta el tiempo marcado"]},
"Suspension Low Back Stretch": {"d":"Agarrado a las cintas, deja caer la cadera atrás dejando que la zona lumbar se abra.","c":["Deja que la espalda se redondee: aquí sí","Brazos estirados","20-30 segundos"]},
"Half Lord of the Fishes": {"d":"Sentado, cruza una pierna sobre la otra y gira el torso hacia la rodilla cruzada, apoyando el codo.","c":["Crece antes de girar","El giro no es un forcejeo","Cambia de lado"]},
})

TEXTOS.update({
"Kettlebell High Pull": {"d":"Con la kettlebell entre las piernas, da un golpe de cadera y tira hacia arriba llevando el codo alto, a la altura del hombro.","c":["El impulso sale de la cadera, no del brazo","El codo acaba alto y por fuera","Deja que baje sola, acompañándola"]},
})
